FROM ngrok/ngrok:3

USER root

# copy in our script
COPY entrypoint.sh /entrypoint.sh

# ensure it can run
RUN chmod +x /entrypoint.sh

# switch back to the ngrok user for runtime safety
USER ngrok

# use our script as the container’s entrypoint
ENTRYPOINT ["/entrypoint.sh"]
