"""initial tables

Revision ID: b73282c5dc65
Revises: 
Create Date: 2025-06-22 22:06:07.730171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73282c5dc65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_detail',
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=100), nullable=True),
    sa.Column('api_call_string', sa.String(length=1000), nullable=True),
    sa.Column('api_param1', sa.String(length=100), nullable=True),
    sa.Column('api_param2', sa.String(length=100), nullable=True),
    sa.Column('api_param3', sa.String(length=100), nullable=True),
    sa.Column('api_param4', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_table('city_detail',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('ayanam_detail',
    sa.Column('ayanam_id', sa.Integer(), nullable=False),
    sa.Column('ayanam_name', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_detail.city_id'], ),
    sa.PrimaryKeyConstraint('ayanam_id')
    )
    op.create_table('message_log',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.JSON(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api_detail.api_id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city_detail.city_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('ritu_detail',
    sa.Column('ritu_id', sa.Integer(), nullable=False),
    sa.Column('ritu_name', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_detail.city_id'], ),
    sa.PrimaryKeyConstraint('ritu_id')
    )
    op.create_table('user_detail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('obsoleted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_detail.city_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_detail')
    op.drop_table('ritu_detail')
    op.drop_table('message_log')
    op.drop_table('ayanam_detail')
    op.drop_table('city_detail')
    op.drop_table('api_detail')
    # ### end Alembic commands ###
